pip install discord
pip install colorama
pip install Fore
pip install Style
pip install requests
pip install threading
pip install os
pip install json
pip install random
pip install time
pip install asyncio
pip install itertools
pip install cycle
pip install pystyle
pip install Colors
pip install Colorate
pip install Center
pip install time
pip install datetime
pip install strftime
pip install gmtime